# Generated by Django 4.2.15 on 2024-12-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('Projects', 'Projects')], max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_access_level',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('ADMIN', 'ADMIN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='group',
            field=models.CharField(choices=[('FEATURED', 'FEATURED'), ('POPULAR', 'POPULAR'), ('LATEST', 'LATEST')], max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_layout',
            field=models.CharField(choices=[('home', 'home'), ('gallery', 'gallery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('PHOTOGALLERY', 'PHOTOGALLERY'), ('EVENTS', 'EVENTS'), ('NEWS', 'NEWS'), ('PRODUCTCATALOG', 'PRODUCTCATALOG'), ('BLOG', 'BLOG')], max_length=50),
        ),
    ]
