# Generated by Django 4.2.15 on 2024-12-19 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0002_imageupload_alter_page_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=255)),
                ('tech_stack', models.CharField(help_text='Technologies used (comma-separated)', max_length=255)),
                ('description', models.TextField(help_text='Short description of the project')),
                ('body', models.TextField(help_text='Detailed project body content')),
                ('extra_body', models.TextField(blank=True, help_text='Additional details (optional)', null=True)),
                ('project_link', models.URLField(blank=True, help_text='Link to the project (if applicable)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a slider image', upload_to='slider_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='scms.ourproject')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a gallery image', upload_to='gallery_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='scms.ourproject')),
            ],
        ),
    ]
