# Generated by Django 4.2.15 on 2024-12-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0003_ourproject_sliderimage_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproject',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from title)', max_length=255, unique=True),
        ),
    ]
