# Generated by Django 4.2.15 on 2024-12-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0004_ourproject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproject',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the project', null=True, upload_to='thumbnails/'),
        ),
    ]
