# Generated by Django 4.2.15 on 2024-12-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0005_ourproject_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title (e.g., Software Engineer)', max_length=255)),
                ('job_type', models.CharField(choices=[('FULLTIME', 'FULLTIME'), ('PARTTIME', 'PARTTIME'), ('INTERNSHIP', 'INTERNSHIP')], help_text='Type of job', max_length=255)),
                ('requirement', models.CharField(choices=[('IMMEDIATE', 'IMMEDIATE')], help_text="Urgency of the requirement (e.g., 'Immediate')", max_length=100)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('experience_required', models.CharField(choices=[('6 MONTHS', '6 MONTHS'), ('1 YEAR', '1 YEAR'), ('1.5 YEAR', '1.5 YEAR'), ('2 YEARS', '2 YEARS')], help_text="Relevant experience (e.g., '1 year and above')", max_length=100)),
                ('responsibilities', models.TextField(help_text='Key responsibilities of the job')),
                ('qualifications', models.TextField(choices=[], help_text='Required qualifications')),
                ('posted_date', models.DateField(auto_now_add=True, help_text='Date the job was posted')),
                ('last_date_to_apply', models.DateField(help_text='Deadline for job applications')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the job posting is active')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='page_layout',
            field=models.CharField(choices=[('home', 'home'), ('gallery', 'gallery'), ('PROJECTS', 'PROJECTS'), ('dynamicpage', 'dynamicpage')], max_length=50),
        ),
    ]
