# Generated by Django 4.2.15 on 2024-12-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0007_alter_career_experience_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='last_date_to_apply',
            field=models.DateField(blank=True, help_text='Deadline for job applications'),
        ),
        migrations.AlterField(
            model_name='career',
            name='qualifications',
            field=models.CharField(choices=[('B. SC Computers', 'B. SC Computers'), ('B. Tech CSC', 'B. Tech CSC')], help_text='Educational Qualifications', max_length=255),
        ),
    ]
