# Generated by Django 4.2.15 on 2024-12-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0013_gallery_alter_news_options_gallerymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_thumbnails/'),
        ),
    ]
