# Generated by Django 4.2.15 on 2024-12-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0014_gallery_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='event_manager_avatars/')),
                ('contact', models.CharField(max_length=15)),
                ('alt_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('calling_timings', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event Manager',
                'verbose_name_plural': 'Event Managers',
            },
        ),
    ]
