# Generated by Django 4.2.15 on 2024-12-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0015_eventmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('seotitle', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('body1', models.TextField(blank=True, null=True)),
                ('body2', models.TextField(blank=True, null=True)),
                ('extra_body', models.TextField(blank=True, null=True)),
                ('event_invitation', models.FileField(blank=True, null=True, upload_to='event_invitations/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='event_brochures/')),
                ('active', models.BooleanField(default=True)),
                ('event_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scms.eventmanager')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
