# Generated by Django 4.2 on 2025-01-29 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scms', '0016_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_layout',
            field=models.CharField(choices=[('home', 'home'), ('gallery', 'gallery'), ('PROJECTS', 'PROJECTS'), ('dynamicpage', 'dynamicpage'), ('twocloumnpage', 'twocloumnpage')], max_length=50),
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture of the professor', null=True, upload_to='member_profiles/')),
                ('department', models.CharField(help_text='Department of the professor (e.g., Computer Science)', max_length=100)),
                ('designation', models.CharField(help_text='Designation (e.g., Assistant Professor, Lecturer)', max_length=100)),
                ('contact_number', models.CharField(blank=True, help_text='Contact number of the professor', max_length=15, null=True)),
                ('office_address', models.TextField(blank=True, help_text='Office address of the professor', null=True)),
                ('bio', models.TextField(blank=True, help_text='Short bio of the professor', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date the professor joined the system')),
                ('active', models.BooleanField(default=True, help_text='Whether the professor is currently active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
