# Generated by Django 4.2 on 2025-03-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0020_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(help_text='Unique subject code (e.g., MATH101)', max_length=50, unique=True)),
                ('credits', models.IntegerField(default=3, help_text='Number of credits for the subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
    ]
