# Generated by Django 4.2 on 2025-03-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0021_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects taught by the professor', to='scms.subject'),
        ),
    ]
