# Generated by Django 4.2 on 2025-03-25 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scms', '0022_memberprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scms.subject'),
        ),
    ]
